/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: calc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "calc.pb-c.h"
void   rpmsg__calc__v1__calc_request__init
                     (Rpmsg__Calc__V1__CalcRequest         *message)
{
  static const Rpmsg__Calc__V1__CalcRequest init_value = RPMSG__CALC__V1__CALC_REQUEST__INIT;
  *message = init_value;
}
size_t rpmsg__calc__v1__calc_request__get_packed_size
                     (const Rpmsg__Calc__V1__CalcRequest *message)
{
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpmsg__calc__v1__calc_request__pack
                     (const Rpmsg__Calc__V1__CalcRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpmsg__calc__v1__calc_request__pack_to_buffer
                     (const Rpmsg__Calc__V1__CalcRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpmsg__Calc__V1__CalcRequest *
       rpmsg__calc__v1__calc_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpmsg__Calc__V1__CalcRequest *)
     protobuf_c_message_unpack (&rpmsg__calc__v1__calc_request__descriptor,
                                allocator, len, data);
}
void   rpmsg__calc__v1__calc_request__free_unpacked
                     (Rpmsg__Calc__V1__CalcRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpmsg__calc__v1__calc_response__init
                     (Rpmsg__Calc__V1__CalcResponse         *message)
{
  static const Rpmsg__Calc__V1__CalcResponse init_value = RPMSG__CALC__V1__CALC_RESPONSE__INIT;
  *message = init_value;
}
size_t rpmsg__calc__v1__calc_response__get_packed_size
                     (const Rpmsg__Calc__V1__CalcResponse *message)
{
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpmsg__calc__v1__calc_response__pack
                     (const Rpmsg__Calc__V1__CalcResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpmsg__calc__v1__calc_response__pack_to_buffer
                     (const Rpmsg__Calc__V1__CalcResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpmsg__Calc__V1__CalcResponse *
       rpmsg__calc__v1__calc_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpmsg__Calc__V1__CalcResponse *)
     protobuf_c_message_unpack (&rpmsg__calc__v1__calc_response__descriptor,
                                allocator, len, data);
}
void   rpmsg__calc__v1__calc_response__free_unpacked
                     (Rpmsg__Calc__V1__CalcResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpmsg__calc__v1__calc_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue rpmsg__calc__v1__calc_request__op__enum_values_by_number[4] =
{
  { "Sum", "RPMSG__CALC__V1__CALC_REQUEST__OP__Sum", 0 },
  { "Sub", "RPMSG__CALC__V1__CALC_REQUEST__OP__Sub", 1 },
  { "Mul", "RPMSG__CALC__V1__CALC_REQUEST__OP__Mul", 2 },
  { "Div", "RPMSG__CALC__V1__CALC_REQUEST__OP__Div", 3 },
};
static const ProtobufCIntRange rpmsg__calc__v1__calc_request__op__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex rpmsg__calc__v1__calc_request__op__enum_values_by_name[4] =
{
  { "Div", 3 },
  { "Mul", 2 },
  { "Sub", 1 },
  { "Sum", 0 },
};
const ProtobufCEnumDescriptor rpmsg__calc__v1__calc_request__op__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rpmsg.calc.v1.CalcRequest.Op",
  "Op",
  "Rpmsg__Calc__V1__CalcRequest__Op",
  "rpmsg.calc.v1",
  4,
  rpmsg__calc__v1__calc_request__op__enum_values_by_number,
  4,
  rpmsg__calc__v1__calc_request__op__enum_values_by_name,
  1,
  rpmsg__calc__v1__calc_request__op__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpmsg__calc__v1__calc_request__field_descriptors[3] =
{
  {
    "op",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Rpmsg__Calc__V1__CalcRequest, op),
    &rpmsg__calc__v1__calc_request__op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpmsg__Calc__V1__CalcRequest, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpmsg__Calc__V1__CalcRequest, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpmsg__calc__v1__calc_request__field_indices_by_name[] = {
  1,   /* field[1] = a */
  2,   /* field[2] = b */
  0,   /* field[0] = op */
};
static const ProtobufCIntRange rpmsg__calc__v1__calc_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpmsg__calc__v1__calc_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpmsg.calc.v1.CalcRequest",
  "CalcRequest",
  "Rpmsg__Calc__V1__CalcRequest",
  "rpmsg.calc.v1",
  sizeof(Rpmsg__Calc__V1__CalcRequest),
  3,
  rpmsg__calc__v1__calc_request__field_descriptors,
  rpmsg__calc__v1__calc_request__field_indices_by_name,
  1,  rpmsg__calc__v1__calc_request__number_ranges,
  (ProtobufCMessageInit) rpmsg__calc__v1__calc_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpmsg__calc__v1__calc_response__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpmsg__Calc__V1__CalcResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpmsg__calc__v1__calc_response__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange rpmsg__calc__v1__calc_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpmsg__calc__v1__calc_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpmsg.calc.v1.CalcResponse",
  "CalcResponse",
  "Rpmsg__Calc__V1__CalcResponse",
  "rpmsg.calc.v1",
  sizeof(Rpmsg__Calc__V1__CalcResponse),
  1,
  rpmsg__calc__v1__calc_response__field_descriptors,
  rpmsg__calc__v1__calc_response__field_indices_by_name,
  1,  rpmsg__calc__v1__calc_response__number_ranges,
  (ProtobufCMessageInit) rpmsg__calc__v1__calc_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
