# --- Nanopb wiring ---
CFLAGS += -I$(CURDIR)/vendor/nanopb -I$(CURDIR)/generated
SRCS   += $(CURDIR)/vendor/nanopb/pb_common.c \
          $(CURDIR)/vendor/nanopb/pb_decode.c \
          $(CURDIR)/vendor/nanopb/pb_encode.c \
          $(CURDIR)/generated/calc.pb.c
