[advisories]
vulnerability = "deny"
unmaintained = "all"
yanked        = "warn"
unsound       = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
