name: afl-smoke

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  afl:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y afl++ qemu-user-static
          rustup toolchain install stable
          rustup default stable

      - name: Build (release)
        run: cargo build --release

      - name: Seed corpus
        run: |
          mkdir -p seeds
          printf "00\n"   > seeds/00.hex
          printf "0A0B\n" > seeds/ab.hex

      - name: AFL for 60s (tolerant)
        run: |
          set -euo pipefail
          mkdir -p out
          timeout 60s afl-fuzz -i seeds -o out -- ./target/release/linux_gateway --decode @@ || true

      - name: Upload AFL output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: afl-out-${{ github.run_id }}
          path: out
          if-no-files-found: ignore
          retention-days: 7
