name: afl-nightly
on:
  schedule: [ { cron: "0 3 * * *" } ]
  workflow_dispatch: {}
permissions: { contents: read }

jobs:
  afl:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install AFL++ (QEMU mode)
        run: |
          sudo apt-get update
          sudo apt-get install -y afl++ clang qemu-user-static

      - name: Build target
        run: cargo build --release

      - name: Ensure seed corpus
        run: |
          mkdir -p fuzz/seeds
          ls -1 fuzz/seeds/* >/dev/null 2>&1 || echo 00 > fuzz/seeds/min.hex

      - name: Fuzz 20m (non-blocking)
        run: |
          mkdir -p fuzz/out
          afl-fuzz -Q -V 1200 -i fuzz/seeds -o fuzz/out -- \
            target/release/linux_gateway --decode @@ || true
          # always have at least one file so upload-artifact doesn't error
          touch fuzz/out/.keep

      - name: Upload AFL output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: afl-out-${{ github.run_id }}
          path: fuzz/out/**
          if-no-files-found: warn
