name: afl-nightly
on:
  schedule: [{ cron: "0 3 * * *" }]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  afl:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install AFL++ & protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y afl++ clang protobuf-compiler
          protoc --version

      - name: Build target (release)
        run: cargo build --release

      - name: Seed corpus
        run: |
          mkdir -p fuzz/seeds
          printf '0A0B0C\n0001020304\n' > fuzz/seeds/seed.txt

      - name: Fuzz for 20 minutes (non-blocking)
        env:
          AFL_SKIP_CPUFREQ: "1"
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: "1"
          AFL_NO_UI: "1"
        run: |
          mkdir -p fuzz/out
          afl-fuzz -V 1200 -i fuzz/seeds -o fuzz/out -- \
            target/release/linux_gateway --decode @@ || true

      - name: Upload AFL output (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: afl-out-${{ github.run_id }}
          path: fuzz/out/
          if-no-files-found: ignore
