- name: Pack AFL artifacts (queue + fastresume)
  if: always()
  run: |
    mkdir -p afl_artifacts
    tar -C afl_out -czf "afl_artifacts/afl-out-${{ github.run_id }}.tar.gz" \
      default/queue default/fastresume.bin

- name: Upload AFL artifacts (tarball)
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: "afl-out-${{ github.run_id }}"
    path: "afl_artifacts/afl-out-${{ github.run_id }}.tar.gz"
    if-no-files-found: warn
