name: afl-nightly
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  afl:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install AFL++ & protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y afl++ clang protobuf-compiler

      - name: Build target (release)
        run: cargo build --release

      - name: Seed corpus
        run: |
          mkdir -p fuzz/seeds
          printf '0A0B0C\n0001020304\n' > fuzz/seeds/seed.txt

      - name: Fuzz 20m (non-blocking)
        env:
          AFL_SKIP_CPUFREQ: "1"
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: "1"
          AFL_NO_UI: "1"
        run: |
          mkdir -p fuzz/out
          afl-fuzz -V 1200 -i fuzz/seeds -o fuzz/out -- \
            target/release/linux_gateway --decode @@ || true

      - name: Tar AFL output (always)
        if: always()
        run: |
          mkdir -p artifacts
          if [ -d fuzz/out ]; then
            tar -C fuzz -czf artifacts/afl-out-${GITHUB_RUN_ID}.tgz out
          else
            tar -czf artifacts/afl-out-${GITHUB_RUN_ID}.tgz --files-from /dev/null
          fi

      - name: Upload AFL archive (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: afl-out-${{ github.run_id }}
          path: artifacts/afl-out-${{ github.run_id }}.tgz
          compression-level: 0
