name: afl-nightly
on:
  schedule: [ { cron: "0 3 * * *" } ]   # 03:00 UTC nightly
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  afl:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install deps (AFL++ & protoc)
        run: |
          sudo apt-get update
          sudo apt-get install -y afl++ clang protobuf-compiler
      - name: Build target (release)
        run: cargo build --release
      - name: Ensure seeds
        run: mkdir -p fuzz/seeds
      - name: Fuzz for 20 minutes (non-blocking)
        env:
          AFL_SKIP_CPUFREQ: "1"
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: "1"
          AFL_NO_UI: "1"
        run: |
          mkdir -p fuzz/out
          afl-fuzz -V 1200 -i fuzz/seeds -o fuzz/out -- \
            target/release/linux_gateway --decode @@ || true
      - name: Tar AFL output
        if: always()
        id: pack
        run: |
          mkdir -p upload
          tar -czf "upload/afl-out-${GITHUB_RUN_ID}.tgz" -C fuzz/out .
          if compgen -G "fuzz/out/crashes/*" > /dev/null; then
            echo "has_crashes=yes" >> "$GITHUB_OUTPUT"
            echo "crash_count=$(find fuzz/out/crashes -type f | wc -l | tr -d ' ')" >> "$GITHUB_OUTPUT"
          else
            echo "has_crashes=no" >> "$GITHUB_OUTPUT"
            echo "crash_count=0" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: afl-out-${{ github.run_id }}
          path: upload/*.tgz
      - name: File issue if crashes
        if: steps.pack.outputs.has_crashes == 'yes'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue create \
            --title "AFL crash: ${{ steps.pack.outputs.crash_count }} inputs (nightly $GITHUB_RUN_ID)" \
            --body  "Nightly AFL found **${{ steps.pack.outputs.crash_count }}** crashing inputs.
                     Artifact: \`afl-out-$GITHUB_RUN_ID\`" \
            --label bug,security,fuzzing
