name: afl-smoke
on:
  pull_request:
  push:
    branches: [ main, "ci/**", "chore/**", "feat/**" ]

jobs:
  afl:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-afl
        run: cargo install cargo-afl

      - name: Build harness (AFL-instrumented)
        working-directory: afl-harness
        run: cargo afl build --release

      - name: Run AFL smoke (45s)
        run: |
          mkdir -p afl_out
          cargo afl fuzz \
            -i afl_corpus_min \
            -o afl_out \
            -V 45 \
            -- ./afl-harness/target/release/afl-harness

      - name: Upload AFL artifacts (queue, findings)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: afl-out-${{ github.run_id }}
          path: |
            afl_out/default/queue
            afl_out/default/fastresume.bin
          if-no-files-found: warn
