name: CI (build + test + fuzz)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --locked --all
      - name: Test
        run: cargo test --locked --all

  fuzz:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      # Nightly for sanitizer flags; cargo-fuzz uses nightly.
      - uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Build fuzz target (frame_decode)
        run: |
          cd fuzz
          cargo fuzz build frame_decode

      # Optional: ensure corpus dirs exist so later tar commands don't fail
      - name: Ensure corpus dirs
        run: |
          mkdir -p fuzz/corpus/frame_decode
          mkdir -p fuzz/artifacts/frame_decode

      # Short smoke run so CI finishes fast; keep fuzzing locally for longer
      - name: Run fuzz (60s smoke)
        run: |
          cd fuzz
          cargo fuzz run frame_decode -- -max_total_time=60 -rss_limit_mb=2048 || true

      # >>> IMPORTANT: pack outputs to avoid ':' in file names breaking upload-artifact
      - name: Pack fuzz outputs (avoid ':' filename errors)
        if: always()
        run: |
          mkdir -p ci_artifacts
          [ -d fuzz/corpus/frame_decode ]    && tar -czf ci_artifacts/corpus_frame_decode.tgz    -C fuzz/corpus    frame_decode || true
          [ -d fuzz/artifacts/frame_decode ] && tar -czf ci_artifacts/artifacts_frame_decode.tgz -C fuzz/artifacts frame_decode || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-results-${{ github.run_id }}
          path: ci_artifacts/*
          if-no-files-found: ignore
          retention-days: 14
