name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --all --verbose

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets -- -D warnings

      # --- Coverage (lcov) ---
      - name: Install llvm-tools + cargo-llvm-cov
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
      - name: Coverage (lcov)
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info
      - name: Upload coverage (lcov)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: lcov.info

      # --- JUnit report ---
      - name: Install nightly + cargo2junit
        run: |
          rustup toolchain install nightly
          cargo install cargo2junit
      - name: Tests → JUnit
        run: cargo +nightly test --all -- -Z unstable-options --format json | cargo2junit > junit.xml
      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml

  fuzz-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Run fuzz smoke (20s)
        run: cargo +nightly fuzz run frame_decode -- -max_total_time=20 -print_final_stats=1
      - name: Upload fuzz artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-output
          path: |
            fuzz/corpus/frame_decode
            fuzz/artifacts/frame_decode

  # Gate Renode job on presence of renode/smoke.resc
  check-renode:
    runs-on: ubuntu-latest
    outputs:
      smoke_present: ${{ steps.chk.outputs.present }}
    steps:
      - uses: actions/checkout@v4
      - id: chk
        run: |
          if [ -f renode/smoke.resc ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

  # Run Renode inside Docker so checkout/artifacts work on the host runner
  renode-smoke:
    needs: [check-renode]
    if: ${{ needs.check-renode.outputs.smoke_present == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Renode smoke in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/work" \
            -w /work antmicro/renode:latest \
            bash -lc 'renode -P -e "mach create; quit" | tee renode.log'
      - name: Upload Renode log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: renode-log
          path: renode.log
