name: fuzz
on:
  push:
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use nightly for fuzzing (needed for -Z flags that cargo-fuzz uses)
      - uses: dtolnay/rust-toolchain@nightly

      - name: Install clang/llvm and cargo-fuzz
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm
          cargo install cargo-fuzz

      # Run the frame_decode target for 60s. cargo-fuzz handles RUSTFLAGS/-Z.
      - name: Run cargo-fuzz (frame_decode)
        run: |
          cd fuzz
          cargo +nightly fuzz run frame_decode -- -max_total_time=60 -rss_limit_mb=2048

      # Tar outputs so we don't upload files with ':' in names (GitHub Artifact restriction)
      - name: Package fuzz outputs
        if: always()
        run: |
          mkdir -p fuzz_out
          tar -czf fuzz_out/corpus.tar.gz    -C fuzz corpus/frame_decode  || true
          tar -czf fuzz_out/artifacts.tar.gz -C fuzz artifacts/frame_decode || true

      - name: Upload fuzz results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-results
          path: fuzz_out/
          retention-days: 14
