name: r5-smoke
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  r5:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "R5 skeleton TODO; this job intentionally non-blocking."
