name: r5-smoke
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  r5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protobuf-c toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-c-compiler libprotobuf-c-dev build-essential pkg-config
      - name: Build host smoke
        run: make -C r5 clean host-smoke
      - name: Run host smoke
        run: ./r5/host-smoke
      - name: Upload binary (debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: r5-host-smoke
          path: r5/host-smoke
