name: r5-smoke
on:
  workflow_dispatch:
jobs:
  r5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps (protoc + plugin + headers)
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler protobuf-c-compiler libprotobuf-c-dev build-essential pkg-config
      - name: Build
        run: make -C r5 all V=1
      - name: Run smoke (expect 42)
        run: |
          ./r5/host-smoke | tee /tmp/out.txt
          test "$(cat /tmp/out.txt)" = "42"
