name: Renode Smoke
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - ci/**
# keep your existing jobs below unchanged
# (I'm only showing the trigger block)
