name: renode-smoke
on:
  pull_request:
  push:
    branches: [ main, "ci/**", "chore/**", "feat/**" ]

jobs:
  renode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Renode portable
        run: |
          curl -fsSL https://builds.renode.io/renode-latest.linux-portable.tar.gz -o renode.tar.gz
          tar xzf renode.tar.gz
          echo "$PWD/renode_portable" >> $GITHUB_PATH
      - name: Smoke
        run: renode --version
